package com.knovatik.navadesh.model.social

data class Data(
    val about_me: String?,
    val address: String?,
    val avatar: String?,
    val created_at: String,
    val email: String,
    val email_status: String,
    val facebook_id: String?,
    val facebook_url: String?,
    val google_id: String?,
    val id: String,
    val instagram_url: String?,
    val last_seen: String?,
    val linkedin_url: String?,
    val mobile_no: String?,
    val number_verify: String,
    val otp: String,
    val password: String,
    val pinterest_url: String?,
    val profile_image: String,
    val role: String,
    val show_email_on_profile: String,
    val show_rss_feeds: String,
    val site_color: String?,
    val site_mode: String?,
    val slug: String,
    val status: String,
    val telegram_url: String?,
    val token: String?,
    val twitter_url: String?,
    val user_type: String,
    val username: String,
    val vk_id: String?,
    val vk_url: String?,
    val youtube_url: String?
)